---
window:
  width:       1920
  height:      1080
  x:           0
  y:           0
  transparent: true
  frame:       false
  stacking:    below
  type:        desktop
  reserve:     true
  reserve_bounds:
    top:    80
    bottom: 64
